apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-docker-python-rhtap-three-component-scenarios-nygs
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-usfg-tenant/mc-three-scenarios/devfile-docker-python-rhtap-three-component-scenarios-nygs@sha256:c26b87c948d1e349230d26987ae87e3d7716daa9da6cbac9821e30cdd4f4131a
        name: my-python
        resources: {}
status: {}
